### ISSUE TITLE
设计器‘’日期范围‘’怎么实现 DateTimePicker 默认起止时间

### ISSUE THREAD

**Issue by ThreeLambs** [vform666/variant-form#10]

**Comment by ThreeLambs** [comment]
<span class="demonstration">起始日期时刻为 12:00:00，结束日期时刻为 08:00:00</span>
    <el-date-picker
      v-model="value2"
      type="datetimerange"
      align="right"
      start-placeholder="开始日期"
      end-placeholder="结束日期"
      :default-time="['12:00:00', '08:00:00']">
    </el-date-picker>

**Comment by vform666** [comment]
这需要给组件增加新的属性设置，用来存储默认起止时间值。

**Comment by vform666** [comment]
@ThreeLambs 上次那个按钮的问题解决了么？
