### ISSUE TITLE
上传文件组件 文件类型问题

### ISSUE THREAD

**Issue by JackGirl** [vform666/variant-form#11]
1.上传组件选择jpg  上传jpg 类型报错 不支持 下拉选择的jpg 对应的值为jpeg 
![0c20f9dd87eb44aa0d2a91165d14c56](https://user-images.githubusercontent.com/26519894/167816108-d8464c57-052a-45a4-a44c-af81fe04f582.png)
2.上传组件 默认勾选的xls doc 去掉勾选下拉没有选择项
![image](https://user-images.githubusercontent.com/26519894/167816141-92aa4f2e-ef5c-4e66-8421-c3177c4b6817.png)
![1652260931(1)](https://user-images.githubusercontent.com/26519894/167816197-172ff7ba-0b89-41d1-ac66-c3119c0f4536.png)

**Comment by vform666** [comment]
已修复，请拉取最新源码试试。
请反馈后续情况。
