### ISSUE TITLE
使用sub-form功能时，“操作”“新增+”可以修改文字么？

### ISSUE THREAD

**Issue by Tyran820** [vform666/variant-form#13]
大佬你好，我是个前端、VUE的初学者。
首先感谢您的项目帮我这种初学者省了好多事。
我这边有个问题，我在使用sub-form功能时，会有“操作”，“新增+”的提示和按钮出现，我可以更改这种提示和按钮的文字么？

**Comment by vform666** [comment]
可以修改的，Pro版本提供了子表单组件源码。
