### ISSUE TITLE
如果完全开源，用的人当然会多。既然是有收费，免费就留bug，让你订阅收费版

### ISSUE THREAD

**Issue by mylittlekingkong** [vform666/variant-form#15]

**Comment by mylittlekingkong** [comment]
不过免费版先用着也是不错的，如果要求很高，公司很重试，买个订阅版的支持下。也好

**Comment by mylittlekingkong** [comment]
前提是公司肯给花钱哦

**Comment by vform666** [comment]
开源版就当回馈社会吧，让喜欢和愿意折腾的人去找些乐了，加bug来强求用户订阅收费版并不可取。

用户之所以要订阅收费版，是因为收费版提供了他们所需要的价值：高级功能、高阶组件以及稳定可靠的技术支持。
顺便说一句，我们的Pro用户很多是个人付费订阅的。
