### ISSUE TITLE
少个key

### ISSUE THREAD

**Issue by RainyNight9** [vform666/variant-form#7]
src/components/form-designer/widget-panel/index.vue      
62行代码 '<el-card :bord-style="{ padding: '0' }" shadow="hover" class="ft-card">' 少个key

**Comment by vform666** [comment]
已修复，感谢提醒。

**Comment by RainyNight9** [comment]
好几个地方都不没有key

**Comment by vform666** [comment]
> 

方便都指出来么？我一起补上。
