### ISSUE TITLE
组件名称怎么和数据库字段建立对应关系？

### ISSUE THREAD

**Issue by liuxm1218** [vform666/variant-form#8]
如题，文档里field-list-api在哪里配置？主子表涉及多表的话，如何跟数据库建立对应关系？

**Comment by vform666** [comment]
field-list-api是配置在v-form-designer组件上：
<v-form-designer ref="vfDesigner" :field-list-api="fieldListApi" />

主从表结构可以用子表单，不过在子表单在开源版没提供哈。
有需要的话可以加群咨询。
