### ISSUE TITLE
umd模式 工具按钮显示乱七八糟

### ISSUE THREAD

**Issue by ThreeLambs** [vform666/variant-form#9]
浏览器script标签引入，默认没有显示一个工具按钮。
1.工具按钮配置和文档不对应，乱。
2.分辨率小于1366 自定义插槽按钮位置偏移，明明有空位置。分辨率1366*768，左侧一个菜单栏，vForm 自定义按钮就。。。
![Snipaste_2022-01-26_14-30-19](https://user-images.githubusercontent.com/23123048/151114725-24f8db9c-b28a-4af6-a81b-11b56cffb64e.png)
![Snipaste_2022-01-26_14-36-48](https://user-images.githubusercontent.com/23123048/151115114-8f798136-0359-4008-ac62-3a261c353924.png)

``` 
  designerConfig: {
            externalLink: true,
            formTemplates: true,
            eventCollapse: true,
            clearDesignerButton: true,//是否显示清空设计器按钮
            previewFormButton: false, //是否显示预览表单按钮
            languageMenu: true,  //是否显示语言切换菜单    
            exportJsonButton: false,  //是否显示导出JSON器按钮
            exportCodeButton: true,  //是否显示导出代码按钮
            generateSFCButton: false,  //是否显示生成SFC按钮 
          }

```

**Comment by vform666** [comment]
拉取最新版本代码哈，配置designer-config属性的下述两个参数值（数值型，单位为像素）：
toolbarMinWidth（默认值300）、toolbarMaxWidth（默认值420）。

**Comment by vform666** [comment]
>>浏览器script标签引入，默认没有显示一个工具按钮。
>>1.工具按钮配置和文档不对应，乱。

这个问题原因大概是你引入CDN上的文件不是最新版，请自行拉取源码，打包后私有部署哈。

**Comment by ThreeLambs** [comment]
咋Close了，你试了吗？
我先按文档步骤做的：
```
1. git克隆VFormBuilds：https://gitee.com/vdpadmin/VFormBuilds
2. 把dist目录下6个文件上传到Web服务器 
```
后来又拉取variant-form源码编译 npm run lib 的都是有问题的。

**Comment by cnx2016** [comment]
>>工具按钮配置和文档不对应
这个能具体说明一下么，我测试没有发现问题。

按钮错位问题请设置toolbarMaxWidth（默认值420），适当调大些。

**Comment by cnx2016** [comment]
> 咋Close了，你试了吗？ 我先按文档步骤做的：
> 
> ```
> 1. git克隆VFormBuilds：https://gitee.com/vdpadmin/VFormBuilds
> 2. 把dist目录下6个文件上传到Web服务器 
> ```
> 
> 后来又拉取variant-form源码编译 npm run lib 的都是有问题的。

不好意思，这个仓库没有同步更新，刚刚同步了，请拉取一下。
https://gitee.com/vdpadmin/VFormBuilds

**Comment by ThreeLambs** [comment]
见了鬼了，没啥用啊！你看看我是哪个单词写错了吗？ 啥按钮都没有哦
```html
 <v-form-designer ref="vfDesigner" :designer-config="designerConfig">
      <!-- 自定义按钮插槽演示 -->
      <!-- <template #customToolButtons>
        <el-button type="text" @click="saveFormJson"><i class="el-icon-finished"> </i>保存</el-button>
      </template> -->
    </v-form-designer>
 designerConfig: {
            externalLink: false,
            formTemplates: true,
            eventCollapse: true,
            clearDesignerButton: true,
            previewFormButton: true,
            languageMenu: true,  //是否显示语言切换菜单   
            importJsonButton: true,  //是否显示导入JSON按钮
            exportJsonButton: true,  //是否显示导出JSON器按钮
            exportCodeButton: true,  //是否显示导出代码按钮
            generateSFCButton: true,  //是否显示生成SFC按钮 
          }
```
```html
designerConfig: {
            externalLink: false, 
          }
```
![Snipaste_2022-01-30_08-24-03](https://user-images.githubusercontent.com/23123048/151682124-4e1c5510-7f9a-4a73-8e05-536f47d4750c.png)

**Comment by vform666** [comment]
你用Chrome的开发者工具看看HTML结构，看看工具按钮栏有没有生成，估计是换行后被上面的元素挡住了。

**Comment by vform666** [comment]
还没解决的话你加群吧，www.vform666.com官网找下交流群二维码。

**Comment by vform666** [comment]
另外，清空你的浏览器缓存后再试试看。
